package com.pillowapps.liqear.models;

public enum ModeEnum {
    CHARTS, LIBRARY, ARTIST_RADIO, TAG_RADIO, ALBUM_RADIO, RECOMMENDATIONS, RADIOMIX,
    NEIGHBOURS, FRIENDS_LAST, USER_AUDIO_VK, GROUP_VK, FRIENDS_VK, SEARCH_VK, ALBUMS_VK,
    RECOMMENDATIONS_VK, WALL_VK, FAVORITES_VK, TOP_ARTISTS, TOP_TRACKS, FUNKY, ALTERPORTAL,
    POSTHARDCORE, SETLIST, LOCAL_ARTISTS, LOCAL_TRACKS, LOCAL_ALBUMS, FEED_VK, RECENT_LAST, LOVED

}
